### ISSUE TITLE
malformed URL formatting

### ISSUE THREAD

**Issue by wohfpb** [jmcnamara/pod-simple-wiki#12]
I'm getting bad URL formatting with --style mediawiki

### POD source
```
=over

=item * L<Google|http://www.google.com>

=item * L<Google(s)|https://www.google.com>

=back
```
### perldoc displays

       ?   Google <http://www.google.com>

       ?   Google(s) <https://www.google.com>

### pod2wiki command

    pod2wiki --style mediawiki ~/scratch/example_pod.pl

### pod2wiki outputs
```
* [[http:#/www.google.com|Google]]
* [[https:#/www.google.com|Google(s)]]
```
### I expect
```
* [http://www.google.com Google]
* [https://www.google.com Google(s)]
```

**Comment by wohfpb** [comment]
Let me know if I can answer questions, provide more info, or help.
I am competent with basic Perl, but would need to brush up on the OOP stuff used in this module.

**Comment by jmcnamara** [comment]
Hi @wohfpb,

Pod::Simple::Wiki is a bit down my priority list these days. Also, the majority of the module predates Pod and Pod::Simple's support for external links!

The best thing to do is to try patch this yourself. Start by adding some test cases for external links based on the examples you show above.

Some of the other Wiki formats have better support for external urls. You could use their tests/code as a starter.

If you run into issues then ping me and I'll try to help you out.

John

**Comment by wohfpb** [comment]
Thanks for the guidance! The script is actually working correctly in the latest (0.16) version. I was using 0.05 when I reported the issue.

What does one need to do to contribute testcases for this syntax? I see where other syntax is tested in t/05_04_mediawiki_links.t

Good news: I learned about Test::More through this exercise. But, I think I need to learn git.

**Comment by jmcnamara** [comment]
> What does one need to do to contribute testcases for this syntax? I see where other syntax is tested in t/05_04_mediawiki_links.t

Yes. It will need some tests like that.

**Comment by jmcnamara** [comment]
@zoffixznet,

Could you help out with this Pod::Simple::Wiki issue?

**Comment by zoffixznet** [comment]
Sure. I'll take a look tomorrow.

**Comment by wohfpb** [comment]
What I propose is just to add the following to t/mediawiki_links.t
But, I don't know how to use git and haven't been able to figure it out today.

```perl
     31     [
     32         "=pod\n\nL<Google|http://www.google.com>." => qq([http://www.google.com Google].\n\n),
     33         'http with text'
     34     ],
     35     [
     36         "=pod\n\nL<Google(s)|https://www.google.com>." => qq([https://www.google.com Google(s)].\n\n),
     37         'https with text'
     38     ],
```
