### ISSUE TITLE
Some Questions / CPAN PR Challenge

### ISSUE THREAD

**Issue by zoffixznet** [jmcnamara/pod-simple-wiki#13]
Hey! :)

I got `Pod-Simple-Wiki` assigned to me for March for [CPAN PR Challenge](http://cpan-prc.org/), so I'm hoping to contribute.

Looking at the list of Issues, RT bugs, and one PR from another person... I was hoping you could offer a guiding light:
1) There's a big PR (#7) from last year. Seems the issue with it is that it just needs to be split up into smaller chunks. Is that code still relevant? I could help out with sorting it out and submitting it in smaller batches.
2) There're a [handful of open RT tickets for the distro](https://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Simple-Wiki), including a couple of patches. Are those still relevant? I could fix up the bugs and submit those patches as PRs.

If you could let me know :)

Thanks.

**Comment by jmcnamara** [comment]
Hi,

Good stuff. Pod::Simple::Wiki could do with a little bit of maintenance.

The issue with PR 7 was there were too many changes in one PR. It contained most of the patches on RT.

A good approach would be to work through the RT issues/fixes and submit separate PRs for each. Start with an easy one such as the typos in #10.

The patches with functional changes should include a test case where possible. There is a straightforward test suite.

The code format is basic perltidy format with the following options: `-mbl=2 -pt=0 -nola`.

If you have any questions just add them to this issue thread.

Thanks for the help,

John

**Comment by jmcnamara** [comment]
Just a note that I've refactored the test cases: renamed and pertidy-ied them.

That may break some of the patches on RT.
