### ISSUE TITLE
[PATCH] fix "POD ERROR"

### ISSUE THREAD

**Issue by gregoa** [jmcnamara/pod-simple-wiki#19]
In Debian we are currently applying the following patch to
Pod-Simple-Wiki.
We thought you might be interested in it too.

    Description: fix POD ERROR:
        Around line 109:
            =over should be: '=over' or '=over positive_number'
            You can't have =items (as at line 114) unless the first thing after
            the =over is an =item
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-11-09
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libpod-simple-wiki-perl.git/plain/debian/patches/pod-syntax.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by jmcnamara** [comment]
Whoops. Embarrassing.

I've push a fix to GitHub and to CPAN.

Thanks for the report and patch.

John

**Comment by gregoa** [comment]
On Mon, 09 Nov 2015 15:01:46 -0800, John McNamara wrote:

> Whoops. Embarrassing.

No worries.
 
> I've push a fix to GitHub and to CPAN.

Thanks, uploaded to Debian/unstable.
 

Cheers,
gregor

-- 
 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: The Beatles: A Hard Day's Night (Shea Stadi
