### ISSUE TITLE
Escaping of Confluence special characters

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/pod-simple-wiki#4]
From Emmanuel Seyman

I became the owner of Pod-Simple-Wiki's package in Fedora a while back and
 discovered we apply a patch that improves the output of the Confluence
 filter (the patch was submitted to you in rt.cpan.org #38833).
 
I've updated the patch to apply to 0.15 (attached to this mail) but I'm not
 sure it is still useful (I don't have a wiki that understands Confluence markup
 to test against).
 
Is there anyway we can :
 
1) agree that the patch is useless and can be dropped from the Fedora package
 
or
 
2) agree that the patch should be included in your module after which it can be
    dropped from the Fedora package

**Comment by zoffixznet** [comment]
To respond to Emmanuel Seyman options: we agree on #2, as without the patch incorrect input is produced, as checked on [Confluence free trial cloud option](https://www.atlassian.com/pt/software/confluence/try)

**Comment by jmcnamara** [comment]
> without the patch incorrect input is produced, as checked on Confluence free trial cloud option

That's good.

In addition to the automated tests I used to test the modules against their corresponding wikis. There is generally a wiki sandbox available somewhere on the web for testing. I also had around 5 wikis running locally at one stage.

I don't know if you have already seen it but to help with testing wiki output the automated tests have a commented out function like this:

```perl
# Output the tests for visual testing in the wiki.
# END{output_tests()};
```
When you run a test with this commented in you get something like this:

```
$ perl -Mlib=lib  t/mediawiki_format.t
1..7
ok 1 - 	Testing: Italic
ok 2 - 	Testing: Bold
ok 3 - 	Testing: Monospace
ok 4 - 	Testing: Filename
ok 5 - 	Testing: Bold Italic
ok 6 - 	Testing: Italic Bold
ok 7 - 	Testing: Single quotes


===Test 1 Italic===
''Foo''

===Test 2 Bold===
'''Foo'''

===Test 3 Monospace===
<tt>Foo</tt>

===Test 4 Filename===
''Foo''

===Test 5 Bold Italic===
'''''Foo'''''

===Test 6 Italic Bold===
'''''Foo'''''

===Test 7 Single quotes===
This is neither '&#39;italic'&#39; nor '&#39;'bold'&#39;'
```

The output could then be pasted into a wiki to check how it rendered.

The commented out code could be implemented in a cleaner way but it wasn't something that was required very often.

Just for your information.

John
